### PR TITLE
ENH: add more error conversions

### PR DESCRIPTION
**Pull request by adler-j**
Adds more conversions, now supports all errors in boost::python and some more.

### CODE REVIEW

**Comment by adler-j** [comment]
Fixed compilation bug and rebased, should be fine now.

**Comment by wjakob** [comment]
what was the issue out of curiosity?

**Comment by adler-j** [comment]
`std::system_error` is not included in the `stdexcept` header, thus compilation failed on Linux (on windows it seems it was magically included somehow). I fixed it by simply removing it for now, extra includes would slow compilation and `system_error` isn't that common. If we want it, we can add an include and conversion from `std::sytem_error` to `SystemError`. Perhaps in the long run you could even allow users to configure this themselves.

**Comment by adler-j** [comment]
A short note is that I fail to compile the library in full (since I'm using VS2013), but i can include it properly in a package. Perhaps keeping this would be a nice feature (for me, I would upgrade if I could, but CUDA does not support VS2015 as of yet) I understand if you do not want that however.

**Comment by wjakob** [comment]
There is some particular line of code that is causing VS2013 to crash -- it might be worth investigating that at some point to see if there is an equivalent statement that still allows it to continue. However, I must admit that it's not a big priority for me (though I would accept a PR if the change is not too big).

**Comment by wjakob** [comment]
thanks!

**Pull request merged**
