### PR TITLE
Vectorize

### PR DESCRIPTION
**Pull request by jmabille**
@wjakob This PR fixes the issue #101. I've added tests in example10 to be able to check further modifications won't break this behavior

### CODE REVIEW

**Comment by jmabille** [comment]
@SylvainCorlay FYI

**Comment by wjakob** [comment]
Holy cow, that patch got very involved -- it will take me a while to get through it. Can you provide a high level overview of what the different classes do? Is there some non-NumPy specific functionality? (since you added separate header files)

**Comment by jmabille** [comment]
There is no non-NumPy specific functionality, however I didn't want to pollute the numpy.h header with iterator classes used for broadcasting, since these iterators are a first version that need to be improved. This would lead to a very big header file if everything was in the numpy header.

About the broadcasting implementation, we first compute the shape of the output array following [numpy broadcasting rules](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html). This is done in the **broadcast** function in **numpy.h**.

The broadcasting is considered to be trivial if on of the following condition is met:
- all input arrays have exactly the same shape
- the input expression contains arrays with the same shape of scalars only
In that case, we rely on the original implementation for computing the output array.

If the broadcasting is not trivial, we rely on iterators and multi-iterator to compute the output array. Basically, iterating through a numpy array is done regarding its shape and strides. The iterator keeps track of a list of coordinate counters. At each iteration, the last coordinate counter is increased, and if it does not reach the dimension size, we increase the underlying buffer by the stride of that dimension. If it reaches the dimension size, we set this counter to 0, decrease the underlying buffer of the right amount (stride[i] * (shape[i]-1)) and increase the next dimension counter. We repeat this operation until a increased counter doesn't reach its dimension size and thus apply the first step.

To improve performance, we can precompute the "backstrides", i.e. the decrease value we must apply to the underlying buffer each time we reach a dimension size. And if we restrict  the iterator to be a forward iterator only, we can even go further by precomputing the sum of strides and backstride and thus storing only one vector. That's what is done in the **common_iterator** class in **array_iterator.h**

Now when we iterate through a numpy expression involving arrays of different shapes, we create a multi_iterator that embeds iterators of every numpy array involved in the expression and the shape of the output array. Since the shape of an input array may differ from the output shape, the multi_iterator has to adapt the iterator of this input array so it thinks it iterates over an array with the output shape. This is done as described below:

- if an input iterator dimension number differs from the output one, length-1 dimensions are added to the input iterator and corresponding strides are set to 0.
- If the i-th dimension size of an input iterator differs form the output i-th dimension size, the i-th stride is set to 0 (because this means the i-th dimension of the input iterator is actually 1, and the underlying buffer should keep its value when iterating in that dimension).

That's the stuff of the **multi_array_iterator** class in **array_iterator.h**

More details about numpy broadcasting can be found here: [Numpy C Code Explanations](http://docs.scipy.org/doc/numpy-1.10.1/reference/internals.code-explanations.html)

Please note the actual implementation compares the shapes of the in put iterators but not their strides. This means non-trivial broadcasting works for arrays with the same memory layout only. Making it work for input arrays with different memory layouts requires more complicated code involving dimension and stride permutation.

**Comment by jmabille** [comment]
Now a few words about **short_vector**. **multi_iterator* *and **common_iterator** classes store vector of strides and shapes, which potentially leads to a lot of dynamic allocation and may hurt performance. In order to limit this overhead, for small dimension arrays (3 or less) we store these vectors in static arrays instead of vectors. This could be done using std::arrays, however this would require to keep a mapping of each dimension with an instantiation of the std::array template. To avoid that, we use a static array with "fake" dynamic size. The array has a static maximum size and its dynamic size must be equal or lower to its static size. This allows to use the same container for storing shapes and strides of different sizes as long as these sizes are not greater than the maximum size (3 by default, but that an arbitrary choice)

**Comment by wjakob** [comment]
Ok, thank you for the extensive clarification, and for spending the time to implement a challenging and helpful feature.

I had a preliminary look at your code and had a two rather superficial comments:

1. there still many tabs left in the code :). I'm also not sure what tab spacing you used, it looked incorrectly formatted on my machine.
2. the formatting convention in pybind11 is that braces occur on the same line as the function declaration / for statement / if statement, etc. It would be great if you could still change this.

The tricks for precomputing backstrides etc. are cool. :)

Regarding the short_vector, I am leaning towards dropping that and always using the std::vector-based implementation. Correct me if I'm wrong -- my assumption is that allocations will only take place once when the iterators are initially created. This is super-cheap (new/delete[] are *fast* these days) and probably very minor compared to the overhead of most Python API calls (and the overhead of passing through pybind11 itself). The motivation of the vectorize function is to greatly accelerate the case where a simple function is run for every entry of a set of large arrays, but the initial setup cost was never a major consideration.

The other reason why I'm leaning towards keeping the implementation shorter is that all of this code will be templated for every function call, so having 3 parallel execution paths is going to have a penalty on the executable size.

Finally: since all of this code is included in numpy.h anways, I'd be happier if this code is part of the same header file. The convention so far was that there is a set of core headerfiles (referenced by pybind11.h) and self-contained "extension" header files that add features like operator support, transparent STL container conversion etc.

What do you think?

Thank you,
Wenzel

**Comment by jmabille** [comment]
No problem, I really enjoyed implementing this feature :)

About the code formatting, I use VS2015 at work and vim at home. My vim is set up so it replace the tab with 4 spaces, however most of the code was done at work and I may have missed some tabs when I updated it at home. Can you confirm the code is well formatted in the example10 files ? These files were updated exclusively at home, that would make me sure my settings are correct.

No problem about the braces, I will change the code so it is compliant with the coding conventions of pybind11.

Regarding your remark about short_vector, you're right, as long as we don't implement post-increment operators of multi_iterator (or any other operation requiring copy), the allocations will take place only once, when the iterator is initially created. But as fast as dynamic allocations could be, they will always be slower than static ones. Now I agree with you on the two following points:

- the performance hurt may be very minor compared to the overhead of Python API calls and all the stuff done in pybind11 before we reach the loop assignment. To be sure, we should do benchmark, but only if we experiment performance issues with the vector-based implementation, and to check dynamic allocations are responsible for this issue.
- the executable size would suffer from keeping the 3 parallel execution paths due to template instantiation.

So it seems my idea of short_vector is a perfect illustration of "Early optimization is the root of all evil" :)
I will remove it and the associated execution path in the vectorize code.

Johan

**Comment by wjakob** [comment]
Fantastic, good that we agree on these points. Did you check in your modified example11.cpp/ref? I didn't notice any changes in that file.

**Comment by jmabille** [comment]
I added the test in example10.py file and the expected outupt in example10.ref but did not modify example10.cpp since it contained everyrthing I needed for my test.

**Comment by wjakob** [comment]
ah, I see -- yes, the Python file looks all good.

**Comment by jmabille** [comment]
Last commit contains code formatting and removal of short_vector. I also removed the template parameter specifying the container in common_iterator and mulmti_iterator since it's not required anymore. and the iterator code has been moved to numpy.h header.

Let me know if I missed something or if you have any additional comment

**Comment by wjakob** [comment]
This looks all good, except for a minor thing in ``setup.py`` where some nonexistent header files are still mentioned. (will fix that in a sec)

**Comment by wjakob** [comment]
(I squashed the commits to keep the history readable)

**Pull request merged**
