### PR TITLE
Set module name for defined functions

### PR DESCRIPTION
**Pull request by SylvainCorlay**
"fixes" #95

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
So modules don't get their `__package__` attribute set either.

**Comment by wjakob** [comment]
huh, what about https://github.com/wjakob/pybind11/blob/master/include/pybind11/pybind11.h#L588?

**Comment by SylvainCorlay** [comment]
(looking into the test failure)

**Comment by SylvainCorlay** [comment]
So apparently you have the following inheritance tree
```
generic_type            cpp_function
     |                        |
     V                        V
  object        <----     function
     |
     V
  handle
```

So `cpp_function` does not get the `__module__` attribute.

**Comment by SylvainCorlay** [comment]
Thanks for the fix.

**Comment by wjakob** [comment]
does this fix the auto doc generation?

**Comment by SylvainCorlay** [comment]
yes. Although I also noticed modules are missing `__package__`, which does not seem to be an issue.

**Comment by wjakob** [comment]
It's an optional attribute AFAIK

**Pull request closed without merging**
