### PR TITLE
Add more integer conversions

### PR DESCRIPTION
**Pull request by mrzv**
Without the changes in `cast.h`, on Linux, I'm unable to return `unsigned long long` from a function (works on Mac). Without the changes to `int_` (at least the constructor from `unsigned`), I cannot do things like `py::int_((uint32_t) 1)`.

### CODE REVIEW

**Comment by mrzv** [comment]
Judging by the failed checks, different compilers behave very differently.

**Comment by wjakob** [comment]
Yeah, it's tricky.. The behavior is also quite different on whether you compile for 32 bit or 64 bit platforms because size_t will change type and potentially collide with some overloads.

**Comment by wjakob** [comment]
By the way: I didn't unterstand why you can't return ``unsigned long long`` on Linux. Isn't that the same as ``uint64_t`` (for which there is a converter)?

**Comment by mrzv** [comment]
I don't understand why it happens, but if I define a function,
```
m.def("test", []() -> unsigned long long { return 1; });
```
compile it on Linux (without adding the lines to `cast.h`) and then call it from Python, I get:
```
In [4]: test()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-ea594c21b25d> in <module>()
----> 1 test()

TypeError: Unable to convert function return value to a Python type! The signature was
        () -> unsigned long long
```

**Comment by wjakob** [comment]
FYI: I committed a few more integer overloads for ``int_::int_()``. I still don't get the issue with regards to returning ``long long`` from your code. Isn't that the same as int64_t? (so the existing overloads should be triggered)

**Comment by mrzv** [comment]
Have you confirmed it? Do you have access to Linux? For me it happens only under Linux (not under OS X), but it does happen. I don't understand it either: as you say, the existing overloads should get triggered. It could be a compiler bug, but it happens both with GCC 5.2 and Clang 3.7.

**Comment by wjakob** [comment]
I could not reproduce it yet. However, I have just committed another attempt to just make integer type handling completely generic using a template construction. Can you please retry with the latest version?

**Comment by wjakob** [comment]
(see 0db14badb4b4354b3feef18fc92e3b44354cf5b4)

**Comment by mrzv** [comment]
Yes, it works! (And a nice solution, I might add. Comparing `sizeof` feels cleaner than explicitly spelling out all the types.) Thanks for fixing it.

**Comment by wjakob** [comment]
Great -- closing this then.

**Pull request closed without merging**
